Define UTF-8 encode probably properly
The previous version of this file defined UTF-8 encoding after the "import", which caused a problem and the interpreter didn't recognize the declared encoding. The error message was:
"
Traceback (most recent call last):
  File "./zayzafoun.py", line 11, in <module>
    app.config.from_object("config")
  File "/usr/local/lib/python2.7/dist-packages/flask/config.py", line 163, in from_object
    obj = import_string(obj)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
  File "/home/ahmed/Projects/zayzafoun/zayzafoun-master/config.py", line 4
SyntaxError: Non-ASCII character '\xd8' in file /home/ahmed/Projects/zayzafoun/zayzafoun-master/config.py on line 4, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

"
Moving the encoding declaration to the top of the file solved the problem.